### ISSUE TITLE
希望增加 Notion 图标。

### ISSUE THREAD

**Issue by uclort** [Koolson/Qure#10]
![notion](https://raw.githubusercontent.com/nlnlnull/Figurebed_Test/master/uPic/notion.png)

**Comment by zhangdi1309** [comment]
![3F6F6DC6-E212-436D-B875-B43548C71745](https://user-images.githubusercontent.com/59596368/81053324-79d09300-8ef7-11ea-8d2b-7642e91e1803.png)
