### ISSUE TITLE
Quantumult X v1.0.18 UI 更新导致 Microsoft 图标显示不正常

### ISSUE THREAD

**Issue by txfengj** [Koolson/Qure#24]
![9690D57F-ABD2-44E9-9D7F-991C48C9D38D](https://user-images.githubusercontent.com/30014542/104106504-66c95a80-52f1-11eb-9bf8-641e33d4bf1d.jpeg)

**Comment by merci-rmvb** [comment]
Dark系列超多图标显示不正常 非dark中Available 显示不出来 大佬肿么办啊

**Comment by Koolson** [comment]
已修复！
